### PR TITLE
Use Yajl to try to avoid JSON encoding errors.

### PR DESCRIPTION
**Pull request by Jorge-Rodriguez**
See uken/fluent-plugin-elasticsearch#19

### CODE REVIEW

**Comment by Jorge-Rodriguez** [comment]
@patant Would you care to review this PR? Releasing this patch will bring our team out of an unholy amount of pain.

**Comment by patant** [comment]
@Jorge-Rodriguez Will look into it as soon as I can.

**Comment by patant** [comment]
@Jorge-Rodriguez Could you please create a branch for the PR

**Comment by Jorge-Rodriguez** [comment]
@patant will do as soon as I get to the office tomorrow. Thank you for your time.

**Comment by Jorge-Rodriguez** [comment]
This PR is replaced by #12

**Pull request closed without merging**
